version: '3.3'

services:
  db:
    container_name: mysql_product
    image: mysql:5.7.27
    restart: always
    environment:
      MYSQL_DATABASE: 'product'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '33066:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - product

volumes:
  db:

networks:
  product: